"""add create_at and update_at column

Revision ID: 0ad92cc1203a
Revises: be52cfe530d9
Create Date: 2026-07-12 17:49:53.254716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad92cc1203a'
down_revision: Union[str, Sequence[str], None] = 'be52cfe530d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('notes', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'update_at')
    op.drop_column('notes', 'create_at')
    # ### end Alembic commands ###
